grails-app/domain/scheater/core/Person.groovy
package scheater.core

import grails.plugin.springsecurity.SpringSecurityService
import groovy.transform.EqualsAndHashCode
import groovy.transform.ToString

@EqualsAndHashCode(includes = 'username')
@ToString(includes = 'username', includeNames = true, includePackage = false)
class Person implements Serializable {

    private static final long serialVersionUID = 1

    SpringSecurityService springSecurityService

    String username
    String password
    String passwordCheck
    Date dateCreated

    boolean enabled = true
    boolean accountExpired = false
    boolean accountLocked = false
    boolean passwordExpired = false

    Set<Authority> getAuthorities() {
        (PersonAuthority.findAllByPerson(this) as List<PersonAuthority>)*.authority as Set<Authority>
    }

    def afterLoad() {
        passwordCheck = password
    }

    def beforeInsert() {
        encodePassword()
    }

    def beforeUpdate() {
        if (isDirty('password')) {
            encodePassword()
        }
    }

    protected void encodePassword() {
        password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
        passwordCheck = password
    }

    static hasOne = [profile: Profile]

    static hasMany = [authorities: Authority]

    static transients = ['springSecurityService', 'passwordCheck']

    static constraints = {
        username blank: false, size: 2..20, matches: /[0-9a-z_-]+/, unique: true
        password nullable: false, blank: false, size: 4..60, password: true, validator: { String val, Person self ->
            val == self.passwordCheck
        }
        passwordCheck bindable: true
        profile nullable: true
    }

    static mapping = {
        autoTimestamp true
        sort 'id'
        order 'desc'
        password column: '`password`'
    }
}

grails-app/controllers/scheater/core/PersonController.groovy
package scheater.core

import grails.plugin.springsecurity.annotation.Secured
import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

@Secured(['ROLE_ADMIN'])
class PersonController {

    PersonService personService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond personService.list(params), model:[personCount: personService.count()]
    }

    def show(Long id) {
        respond personService.get(id)
    }

    def create() {
        respond new Person(params)
    }

    def save(Person person) {
        if (person == null) {
            notFound()
            return
        }

        try {
            personService.save(person)
        } catch (ValidationException e) {
            respond person.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'person.label', default: 'Person'), person.id])
                redirect person
            }
            '*' { respond person, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond personService.get(id)
    }

    def update(Person person) {
        if (person == null) {
            notFound()
            return
        }

        try {
            personService.save(person)
        } catch (ValidationException e) {
            respond person.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'person.label', default: 'Person'), person.id])
                redirect person
            }
            '*'{ respond person, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        personService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'person.label', default: 'Person'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'person.label', default: 'Person'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/person/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="application"/>
        <g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}"/>
        <title>
            <g:message code="default.create.label" args="[entityName]"/>
        </title>
    </head>
    <body>
        <div id="create-person" class="content scaffold-create" role="main">
            <h1 class="page-header">
                <g:message code="default.create.label" args="[entityName]"/>
            </h1>

            <g:hasErrors bean="${this.person}">
                <div class="alert alert-danger" role="alert">
                    <ul>
                        <g:eachError bean="${this.person}" var="error">
                            <li><g:message error="${error}"/></li>
                        </g:eachError>
                    </ul>
                </div>
            </g:hasErrors>

            <g:form action="save" class="form-horizontal">
                <div class="form-group">
                    <label for="username" class="col-md-2 control-label"><g:message code="person.username.label"/></label>
                    <div class="col-sm-4">
                        <g:textField name="username" class="form-control" id="username" value="${params.username}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="password" class="col-md-2 control-label"><g:message code="person.password.label"/></label>
                    <div class="col-sm-4">
                        <g:passwordField name="password" class="form-control" id="password" value="${params.password}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="passwordCheck" class="col-md-2 control-label"><g:message code="person.passwordCheck.label"/></label>
                    <div class="col-sm-4">
                        <g:passwordField name="passwordCheck" class="form-control" id="passwordCheck" value="${params.passwordCheck}"/>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-7">
                        <g:submitButton name="create" class="btn btn-primary" value="${message(code: 'default.button.create.label', default: 'Create')}"/>
                    </div>
                </div>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/person/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="application"/>
        <g:set var="entityName" value="${message(code: 'person.label', default: 'Person')}"/>
        <title>
            <g:message code="default.edit.label" args="[entityName]"/>
        </title>
    </head>
    <body>
        <div id="edit-person" class="content scaffold-edit" role="main">
            <h1 class="page-header">
                <g:message code="default.edit.label" args="[entityName]"/>
            </h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.person}">
                <ul class="errors" role="alert">
                    <g:eachError bean="${this.person}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                    </g:eachError>
                </ul>
            </g:hasErrors>

            <g:form resource="${this.person}" method="PUT" class="form-horizontal">
                <g:hiddenField name="version" value="${this.person?.version}"/>
                <div class="form-group">
                    <label for="name" class="col-md-2 control-label"><g:message code="person.name.label"/></label>
                    <div class="col-sm-4">
                        <g:textField name="profile.name" class="form-control" id="name" value="${this.person.profile?.name}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="email" class="col-md-2 control-label"><g:message code="person.email.label"/></label>
                    <div class="col-sm-4">
                        <g:textField name="profile.email" class="form-control" id="email" value="${this.person.profile?.email}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="phoneNumber" class="col-md-2 control-label"><g:message code="person.phoneNumber.label"/></label>
                    <div class="col-sm-4">
                        <g:textField name="profile.phoneNumber" class="form-control" id="phoneNumber" value="${this.person.profile?.phoneNumber}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="address" class="col-md-2 control-label"><g:message code="person.address.label"/></label>
                    <div class="col-sm-4">
                        <g:textField name="profile.address" class="form-control" id="address" value="${this.person.profile?.address}"/>
                    </div>
                </div>
                <fieldset class="buttons">
                    <input class="btn btn-primary" type="submit"
                           value="${message(code: 'default.button.update.label', default: 'Update')}"/>
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/person/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="application"/>
    <g:set var="entityName" value="${message(code: 'appli.person.label', default: 'Person')}"/>
    <title><g:message code="default.list.label" args="[entityName]"/></title>
</head>

<body>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <a href="${createLink(controller: 'person', action: 'create')}" class="btn btn-primary pull-right">
            <g:message code="default.new.label" args="[message(code: 'appli.person.label')]"/>
        </a>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="page-header"><g:message code="default.list.label" args="[message(code: 'appli.person.label')]"/></h1>
        <g:each var="person" in="${personList}">
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <g:link action="show" id="${person.id}">
                    <div class="person__box">
                        <kbd>${person.username}</kbd>
                        <h6 class="text-muted">${person.authorities.authority.join(' , ')}</h6>

                        <p><abbr title="Date Created"><i class="fa fa-calendar-o"></i></abbr>&nbsp;<g:formatDate
                                date="${person?.dateCreated}"
                                format="${scheater.core.util.PropertyUtils.loadProperty('datetime.format')}"/></p>
                    </div>
                </g:link>
                <div class="person-box__footer">
                    <div class="btn-group">
                        <g:link class="btn btn-danger btn-sm" action="resetPassword" resource="${this.person}">
                            <g:message code="default.button.reset.label" args="[message(code: 'springSecurity.login.password.label')]"/>
                        </g:link>
                    </div>

                    <div class="btn-group">
                        <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#authorityDialog">
                            <g:message code="default.button.change.label" args="[message(code: 'appli.authority.label')]"/>
                        </button>
                    </div>
                </div>
                <!-- authorityDialog -->
                <div class="modal fade" id="authorityDialog" role="dialog">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title">Modal Header</h4>
                            </div>
                            <div class="modal-body">
                                <p>Some text in the modal.</p>
                                <div class="row">
                                    <g:select from="${scheater.core.Authority.list()}" name="authorities"
                                              optionKey="id" optionValue="authority" value="${person.authorities?.id}"
                                              id="authority" class="chosen-authority" multiple="true"
                                              data-placeholder="${message(code: 'person.authority.placeholder')}">
                                    </g:select>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </g:each>
    </div>
</div>
</body>
</html>

grails-app/views/person/show.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="application"/>
    <g:set var="entityName" value="${message(code: 'appli.person.label', default: 'Person')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h1 class="page-header"><g:message code="default.info.label" args="[message(code: 'appli.person.label')]"/></h1>

        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
            <div class="panel panel-default">
                <div class="panel-heading text-center"><i class="fa fa-user-o"></i>&nbsp;${person?.username}</div>
                <div class="panel-body">
                <g:if test="${person.profile}">
                    <p><i class="fa fa fa-address-card-o"></i>&nbsp;<strong>${person.profile?.name}</strong></p>
                    <p><i class="fa fa-phone"></i>&nbsp;${person.profile?.phoneNumber}</p>
                    <p><i class="fa fa-envelope-o"></i>&nbsp;${person.profile?.email}</p>
                    <p><abbr title="${message(code: 'person.lastUpdated.label')}"><i class="fa fa-calendar-o"></i></abbr>&nbsp;<g:formatDate
                            date="${person.profile?.lastUpdated}" format="EEE, MMM dd, yyyy"/></p>
                    <p><i class="fa fa-institution"></i>&nbsp;${person.profile?.address}</p>
                </g:if>
                    <div class="col-sm-6">
                        <g:link class="btn btn-primary btn-sm btn-block" action="edit" resource="${this.person}">
                            <i class="fa fa-edit"></i>&nbsp;<g:message code="default.button.edit.label"/>
                        </g:link>
                    </div>
                    <div class="col-sm-6">
                        <g:link class="btn btn-danger btn-sm btn-block" action="delete" resource="${this.person}"
                                onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
                            <i class="fa fa-remove"></i>&nbsp;<g:message code="default.button.delete.label" default="Delete"/>
                        </g:link>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xs-12 col-sm-6 col-md-8 col-lg-9">
            <div class="activities-box">
                <div class="panel panel-default">
                    <div class="panel-heading text-center">Activities</div>
                    <div class="panel-body">
                        <p class="text-center"><strong>LOADING...</strong></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br>

<div>

</div>
</body>
</html>